# Generated by Django 5.0.6 on 2024-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='content',
            field=models.TextField(default='default content'),
            preserve_default=False,
        ),
    ]
