# Generated by Django 5.0.6 on 2024-06-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='author',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
